import './styles/OurModel.css'

// Lots of garbage text below to demo scrollbar.
// Replace this text with the appropriate information.

const OurModelPage = () => {
    return (
        <div className="ourModelPage">
            <div className="ourModelHeader">
                Our Model
            </div>
            <div className="ourModelTextDisplayContainer">
                <div className="ourModelTextDisplay">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu dictum varius duis at consectetur lorem donec massa. Commodo viverra maecenas accumsan lacus. Eget duis at tellus at urna condimentum mattis. Quam adipiscing vitae proin sagittis nisl rhoncus. Volutpat sed cras ornare arcu dui vivamus arcu. Non curabitur gravida arcu ac tortor. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Consequat interdum varius sit amet. Nullam non nisi est sit amet facilisis magna etiam. Purus semper eget duis at tellus at urna condimentum mattis. Sed adipiscing diam donec adipiscing tristique. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Quisque id diam vel quam elementum. Tortor consequat id porta nibh venenatis cras. Quisque id diam vel quam elementum pulvinar etiam non. Elit scelerisque mauris pellentesque pulvinar.
                    Nunc sed augue lacus viverra vitae congue eu. Quam id leo in vitae. Adipiscing elit pellentesque habitant morbi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Urna porttitor rhoncus dolor purus non enim praesent elementum. Viverra justo nec ultrices dui sapien eget mi proin. Tortor dignissim convallis aenean et. Rutrum quisque non tellus orci ac auctor augue mauris. Laoreet sit amet cursus sit. Ut venenatis tellus in metus vulputate eu scelerisque felis. Laoreet sit amet cursus sit amet dictum sit. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Enim ut tellus elementum sagittis vitae et leo duis ut. Nunc pulvinar sapien et ligula ullamcorper. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Nulla malesuada pellentesque elit eget gravida cum. Consectetur libero id faucibus nisl tincidunt eget nullam non. Sollicitudin nibh sit amet commodo nulla facilisi.
                    Eget duis at tellus at urna condimentum mattis pellentesque. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Orci nulla pellentesque dignissim enim. Ullamcorper malesuada proin libero nunc. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Vitae elementum curabitur vitae nunc sed velit. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. A pellentesque sit amet porttitor eget dolor morbi non. Egestas congue quisque egestas diam in arcu. Quisque egestas diam in arcu cursus euismod. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Amet purus gravida quis blandit. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Tristique magna sit amet purus. Diam maecenas ultricies mi eget mauris. In eu mi bibendum neque egestas. Nec nam aliquam sem et tortor consequat id porta nibh.
                    Proin fermentum leo vel orci porta non pulvinar neque laoreet. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Diam sollicitudin tempor id eu. Leo in vitae turpis massa sed elementum tempus egestas. Sem fringilla ut morbi tincidunt. Rhoncus dolor purus non enim praesent elementum facilisis. Ut tortor pretium viverra suspendisse potenti nullam ac. Tortor posuere ac ut consequat semper. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Risus in hendrerit gravida rutrum quisque non tellus orci. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus.
                    Cras fermentum odio eu feugiat. Dictumst quisque sagittis purus sit. Facilisi morbi tempus iaculis urna. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Mattis aliquam faucibus purus in massa tempor nec feugiat. Nisl suscipit adipiscing bibendum est ultricies integer quis. Nec nam aliquam sem et tortor. At consectetur lorem donec massa sapien faucibus. Nec dui nunc mattis enim ut tellus elementum sagittis vitae. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Porta nibh venenatis cras sed. Aliquet lectus proin nibh nisl condimentum. Purus viverra accumsan in nisl nisi scelerisque eu. Egestas erat imperdiet sed euismod nisi porta lorem. Phasellus faucibus scelerisque eleifend donec.
                    Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Eu volutpat odio facilisis mauris sit amet massa. Duis ut diam quam nulla porttitor. Tincidunt tortor aliquam nulla facilisi cras. Augue ut lectus arcu bibendum at varius vel. Ornare arcu odio ut sem nulla pharetra. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. In ornare quam viverra orci sagittis eu. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Tellus cras adipiscing enim eu turpis egestas.
                    Et tortor at risus viverra adipiscing at in tellus integer. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Risus at ultrices mi tempus. Mi in nulla posuere sollicitudin. Tellus elementum sagittis vitae et leo duis ut. Diam vulputate ut pharetra sit amet aliquam id. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Sed sed risus pretium quam vulputate dignissim. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi.
                    Nisi vitae suscipit tellus mauris a diam maecenas sed. Nullam ac tortor vitae purus faucibus ornare suspendisse. Nec nam aliquam sem et tortor consequat id. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Magna eget est lorem ipsum dolor. Dui ut ornare lectus sit amet. Velit euismod in pellentesque massa. Tortor condimentum lacinia quis vel eros donec ac odio. Aliquet porttitor lacus luctus accumsan tortor posuere. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Eu volutpat odio facilisis mauris sit amet massa vitae.
                    Nulla at volutpat diam ut venenatis tellus in metus. Purus faucibus ornare suspendisse sed nisi lacus sed. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Felis eget nunc lobortis mattis aliquam. Volutpat est velit egestas dui id ornare arcu odio. Massa sed elementum tempus egestas sed sed risus. Integer vitae justo eget magna fermentum iaculis eu non diam. Morbi tristique senectus et netus et malesuada fames ac turpis. Est sit amet facilisis magna etiam. Libero volutpat sed cras ornare. Mauris nunc congue nisi vitae suscipit tellus mauris a diam.
                    Eu mi bibendum neque egestas. Purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae. In est ante in nibh. Venenatis a condimentum vitae sapien pellentesque habitant. Eget duis at tellus at urna condimentum mattis pellentesque. At lectus urna duis convallis convallis tellus id interdum. Gravida rutrum quisque non tellus orci ac auctor augue. Turpis egestas pretium aenean pharetra. Nulla facilisi cras fermentum odio eu feugiat. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Consequat ac felis donec et odio pellentesque diam. Sit amet volutpat consequat mauris. Quis blandit turpis cursus in hac habitasse.
                </div>
            </div>
            <div className="ourModelLinkDisplayContainer">
                <div className="ourModelLinkDisplay">
                    <div className="linkDisplayHeader">
                        Links
                    </div>
                </div>
            </div>
        </div>
    )
}

export default OurModelPage;